### ISSUE TITLE
【質問】改訂版P30-31 ApplicationContext#closeを呼ばなくした理由は？

### ISSUE THREAD

**Issue by kazuki43zoo** [making/hajiboot-samples#33]
ShutdownHookでcloseされるから？

初版ではtry-with-resources句使ってプログラム内で意識的にcloseするコード例になっていたので少し気になりました。DIコンテナとしてはcloseが必要な旨の説明はあった方がよい気がしました。closeする手法として、明示的にcloseする（or try-with-resourcesによるclose含む）やShutdownHootによるcloseがあると思うので。

**Comment by making** [comment]
https://github.com/spring-projects/spring-boot/blob/v1.4.0.RELEASE/spring-boot/src/main/java/org/springframework/boot/SpringApplication.java#L372

`SpringApplication.run`で`ApplicationContext`を作ると`registerShutdownHook`が登録されてるので、余計なことをする必要がなかったのです。

**Comment by kazuki43zoo** [comment]
👍 （だと思ったけど念のためw）

Spring BootからSpringを始める人にApplicationContextは本来closeする必要あるんだよ！！（を知ってもらう意味で軽く説明があってもいいかな〜とは思ったけど、ま〜勝手にやってくれるからいいかw）

**Comment by making** [comment]
ここで出すのは不自然でしょw
