### ISSUE TITLE
改訂版P84 curlでJSON送る時にダブルクォートをエスケープしないで済む方法

### ISSUE THREAD

**Issue by kazuki43zoo** [making/hajiboot-samples#43]
今のままでも何も問題ないですけど、`-d` の 値の括り文字を「`'`」（シングルクォート）にすることで、JSON内の「`"`」（ダブルクォート）を「 `\`」でエスケープする必要がなくなるとおもいます。

**Comment by making** [comment]
コマンドプロンプト使う人がハマるんですよね、それ

**Comment by kazuki43zoo** [comment]
あ・・なるほど。最近wndowsでもgitbash上でしたコマンド使わないからな〜w
