### ISSUE TITLE
P66 data.sql と schema.sqlの作成タイミングについて

### ISSUE THREAD

**Issue by kazuki43zoo** [making/hajiboot-samples#5]
P.66で、この時点では作らないで！とあるが、その後、作るタイミングについては特に言及がない。
2.2.2の最後か、2.2.3の冒頭にやるんだろうな〜というのは想像つくのですが、一応ちょっと気になりました。
＋
このセクションではschema.sqlは不要では？（JPAの機能でテーブルを生成するため）

**Comment by making** [comment]
遅くなりましたが、READMEに追記しました。
