### ISSUE TITLE
改訂版P124 application.propertiesがいきなりyaml形式になっている

### ISSUE THREAD

**Issue by mas178** [making/hajiboot-samples#57]
| 場所 | 誤 | 正 |
| --- | --- | --- |
| P124 | 【application.yml】Basic認証を無効にする<br/>`security.basic.enabled: false` | 【application.properties】Basic認証を無効にする<br/>`security.basic.enabled=false` |

**Comment by making** [comment]
df166dcdc1b991f0defbd4da49a22cc59a45ce5b で修正済み
