### ISSUE TITLE
STS3.8.1 で最初の１章で４０４エラー（解決済）

### ISSUE THREAD

**Issue by vitavita** [making/hajiboot-samples#58]
STS3.8.1 で最初の１章で４０４エラーになってしまいます。
なぜでしょうか。
以下を使用しています。
環境: mac10.11.6
java:  javac 1.8.0_11
Spring Initializr でSpring Boot 1.4.1を使用しています。

失礼しました。上記の件ですが、HajibootApplication.javaに誤記があったため、404が発生していました。こちらのissueを削除する方法はありますか。

**Comment by making** [comment]
誤記はどの部分ですか？
