### ISSUE TITLE
Spring Boot 1.5.2でエラー　P.60　CustomerRepositoryクラス

### ISSUE THREAD

**Issue by crazyquilt** [making/hajiboot-samples#61]
STS3.8.3上で作成しています。
P.60　CustomerRepositoryクラス　initメソッド

``` java
insert = new SimpleJdbcInsert((JdbcTemplate) jdbcTemplate.getJdbcOperations())
```

の行で`”The constructor SimpleJdbcInsert(JdbcTemplate) is undefined”`というエラーが表示されます。

**Comment by making** [comment]
特に問題ないと思いますが・・
