### ISSUE TITLE
ハッシュ化されたユーザーパスワードをSQLのINSERTで設定する方法

### ISSUE THREAD

**Issue by TakahitoDoi** [making/hajiboot-samples#69]
「3.5_hajiboot-security」の「V3__add-user.sql」で、
Pbkdf2PasswordEncoder でハッシュ化したパスワードを次のようにINSERTしている部分ですが、
この「ハッシュ化されたパスワード」は、どうやって作られたものかが分かりませんでした。

```
INSERT INTO users (username, encoded_password) VALUES ('user1', 'ce5f8d0c5790bf82e9b253d362feb51ba02853301ae24149b260bd30acb00f1b2a0d8b18bbff97a9' /*demo*/);
INSERT INTO users (username, encoded_password) VALUES ('user2', 'ce5f8d0c5790bf82e9b253d362feb51ba02853301ae24149b260bd30acb00f1b2a0d8b18bbff97a9' /*demo*/);
```

任意の文字列を次のようにハッシュ化して、そのパスワードをINSERTするようにしましたが、
ハッシュ化された値は実行する都度変わってしまうため、結局その値では、「V3__add-user.sql」にあるようなパスワードの設定はできないように見受けられます。
`System.out.println(new Pbkdf2PasswordEncoder().encode("test"));`

Webで検索もかけてみましたが、どうにも理解ができないため、
ご教授いただけますと幸いです。

**Comment by kazuki43zoo** [comment]
`System.out.println(new Pbkdf2PasswordEncoder().encode("demo"));`した値だと思いますよ。

「同じ生パスワード（例えば `demo`）」をハッシュ化した時に「ハッシュ化後の値」が毎回違うのは、「生パスワード」に「ソルト（`Pbkdf2PasswordEncoder`は8バイトのダンラム値の模様）」を付加した後にハッシュ化しているためです。

ソルトを付与することで、仮に同じパスワードであってもハッシュ化後の値がわかるため、（仮に）ハッシュ化後のパスワードが露出しても、パスワードが悪用（解読）されるリスクは小さくなります。

**Comment by TakahitoDoi** [comment]
回答ありがとうございます。

つまり、私が抜粋したINSERT文に記載されているパスワードは、
ソルト（Salt）を付加しない状態でハッシュ化したパスワード（demo）が記載されている、ということでしょうか？

単純に`System.out.println(new Pbkdf2PasswordEncoder().encode("demo"));`しただけですと、
ランダム値が含まれてしまうことで、INSERT文で記載している 

> 'ce5f8d0c5790bf82e9b253d362feb51ba02853301ae24149b260bd30acb00f1b2a0d8b18bbff97a9' 

と同じ内容とはなりません。それでも、INSERT文で上記の値がdemoとして認識できるということは、
上記の値は、Saltの影響を受けていない値である、と解釈しました。

よって、もしパスワードが「test」であるユーザー「user3」を追加するINSERT文とする場合は、
Saltを付加しないPBKDF2でのハッシュ化をした結果を生成する必要があるということで合っているでしょうか？
その場合、PBKDF2が行っているハッシュ化がどういう方法かを知る必要があるということでしょうか。

**Comment by kazuki43zoo** [comment]
> ソルト（Salt）を付加しない状態でハッシュ化したパスワード（demo）が記載されている、ということでしょうか？

いや、ソルトは（もちろん）付加されてますよ。サンプルでは単に１回作ったパスワード（ハッシュ化後のパスワードも含めて）を複数のユーザで使いわましているだけですね。

> それでも、INSERT文で上記の値がdemoとして認識できるということは、上記の値は、Saltの影響を受けていない値である、と解釈しました。

`Pbkdf2PasswordEncoder`を使用してハッシュ化した値の中には（実は）「ソルト」も含まれており、「ハッシュ済みのパスワード（DBに登録しているパスワード）」からソルトを抜きだすことができる仕組みになっています。`Pbkdf2PasswordEncoder`はパスワードのマッチング処理を行う際に、「入力された生パスワード」に「抜き出したソルト」を付与してハッシュ化してから「DBに登録しているパスワード」と比較することで、パスワードの一致/不一致を判断しています。

> よって、もしパスワードが「test」であるユーザー「user3」を追加するINSERT文とする場合は、
Saltを付加しないPBKDF2でのハッシュ化をした結果を生成する必要があるということで合っているでしょうか？

`Pbkdf2PasswordEncoder`を使ってハッシュ化した値をinsert文の値にする貼り付けるだけです。

**Comment by TakahitoDoi** [comment]
返信遅くなりました。

実際に「Pbkdf2PasswordEncoder」でエンコードした値をユーザーのパスワードに設定してみたところ、正常にログインができました！

ソルト（値はランダム）が含まれたパスワードをハッシュ化することで、人間の目には解読不可能でランダムに変わる文字列になっていたとしても、「getEncodedPassword」で読み取る際は、ソルトが何で、パスワードが何かを区別して読み取ることができる、ということですね。

理解が悪くすみません。非常に助かりました！

**Comment by making** [comment]
Thanks! @kazuki43zoo
