### ISSUE TITLE
3章 型が一致しないエラー

### ISSUE THREAD

**Issue by eewano** [making/hajiboot-samples#72]
当方、windows7を使用しています。
改訂版の77ページにて、CustomerService.java を作成するのですが、引数の不一致及び型が不適合のエラーが出て実行が出来ません。
![error01](https://user-images.githubusercontent.com/9584187/38470155-bbd5533e-3b99-11e8-8f98-56a0cc1ced87.png)
![error02](https://user-images.githubusercontent.com/9584187/38470158-c38e72ea-3b99-11e8-8bb2-da43b7b9eec8.png)
エラー自体が理解出来ない為、行き詰ってしまいました。テキスト通りに進めていますが、何か設定が悪いのか、それともバージョンの違いでエラーになってしまうのかが分かりません。
もし可能であればアドバイス願います。
Spring Tool Suite のバージョンは3.9.3 最新です。

**Comment by making** [comment]
Spring Boot 2.0を使っていません？

**Comment by eewano** [comment]
>Toshiakiさん
はい、調べたら Spring Boot 2.0 です。書籍では 1.4 ですね...。そうなると、やはり 1.4 をインストールし直して進めた方が良いでしょうか？

**Comment by making** [comment]
本書のコードは2.0ではAPI変更のため、一部コンパイルエラーが派生します。
そこの修正をするのが嫌であれば、まずは1.4または1.5で進めることをおすすめします。

pom.xmlのparentのバージョンを2.0.1.RELEASEから1.5.11.RELEASE等に変更してください

**Comment by eewano** [comment]
>Toshiakiさん
バージョンを1.5.11 RELEASE に変更しました。今度は順調に実行が出来ましたので、このバージョンで進めていきます。教えて頂き、どうもありがとうございます。
