### ISSUE TITLE
78ページのCustomerServiceでコンパイルエラー

### ISSUE THREAD

**Issue by tawatana** [making/hajiboot-samples#78]
78ページのCustomerServiceのソース内の以下2箇所でコンパイルエラーとなります。
customerRepository.findOne(id);
customerRepository.delete(id);

エラー内容は「The method findOne(Customer) in the type CrudRepository<Customer,Integer> is not applicable for the arguments (Integer)」です。
deleteも同様です。

解消方法をご教示頂けますでしょうか。
STSのバージョンは3.9.4になります。
よろしくお願い致します。

**Comment by making** [comment]
https://github.com/making/hajiboot-samples/issues/77 と同じですかね

**Comment by tawatana** [comment]
ご回答ありがとうございます。
過去分の確認漏れでお手数お掛けしすみません。
2系用の修正をしてみたところエラーが解消致しました。
