### ISSUE TITLE
@GeneratedValue(strategy=GenerationType.IDENTITY)への修正依頼

### ISSUE THREAD

**Issue by tendenkou** [making/hajiboot-samples#79]
はじめてのSpring Boot 改訂版(第4刷)」を使用しています。

P.65のCustomerクラスの内容ですが、「@GeneratedValue」だと、ID自動採番がされません。

「@GeneratedValue(strategy=GenerationType.IDENTITY)」とすると、ID自動採番がなされて正常に動作します。

使用しているSpringBootのバージョンは、以下の通りです。

```
springBootVersion = '2.1.0.RELEASE'
```

困っている方もいらっしゃると思いますので、以下のファイルの修正を宜しくお願い致します。

```
 hajiboot-samples/chapter02/2.3.2_hajiboot-jpa/src/main/java/com/example/domain/Customer.java

 hajiboot-samples/chapter02/2.3.3_hajiboot-jpa/src/main/java/com/example/domain/Customer.java

 hajiboot-samples/chapter02/2.3.4.1_hajiboot-jpa/src/main/java/com/example/domain/Customer.java

 hajiboot-samples/chapter02/2.3.4.2_hajiboot-jpa/src/main/java/com/example/domain/Customer.java
```

**Comment by making** [comment]
"はじめてのSpring Boot"は2系に対応していません。

動かない、コンパイルできない箇所は指摘いただいた場所のみではありません。

かなり昔ですが、別のブランチに途中まで確認したものがあります。
https://github.com/making/hajiboot-samples/commit/dfce58fcdde654e3739bc747205c2181c3da5a7a#diff-2661a947560c7c43c76d4497e755032d

**Comment by tendenkou** [comment]
>"はじめてのSpring Boot"は2系に対応していません。

そうだったんですね。大変失礼いたしました。
